
dubbo:
  application:
    id: user-server
    name: user-server    
    qosEnable: true
    qosPort: 22223
  registry:
    address: redis://root:pass@192.168.0.116:6379/10
    #address: redis://192.168.1.100:7000

  protocol:
    name: dubbo
    port: 12345    
    #host: dubbo.easex.cn 
    
spring:
  application:
    name: user-server    
